// there are these array methods    
//! push, pop, shift, unshift, splice, slice, concat, join, indexOf, lastIndexOf, includes, reverse, sort, filter, map, reduce, forEach


// example  of array methods
let arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr.push(10)
console.log(arr)
arr.pop()
console.log(arr)
arr.shift()
console.log(arr)
arr.unshift(1)
console.log(arr)
arr.splice(2, 2, 10, 11)
console.log(arr)
arr.slice(2, 4)
console.log(arr)
arr.concat([10, 11, 12])
console.log(arr)
arr.join('-')
console.log(arr)
arr.indexOf(2)
console.log(arr)
arr.lastIndexOf(2)
console.log(arr)
arr.includes(2)
console.log(arr)
arr.reverse()
console.log(arr)
arr.sort()
console.log(arr)
arr.filter((item) => item > 2)
console.log(arr)
arr.map((item) => item * 2)
console.log(arr)
arr.reduce((acc, item) => acc + item)
console.log(arr)
arr.forEach((item) => console.log(item))
console.log(arr)
